feat: add breadcrumbs navigator
graasp/graasp-analytics pull request #129
Opened 2023-03-29 15:36 UTC by rayacers

Add the breadcrumbs navigator.

2023-04-05 07:46 UTC, pyphilia requested changes
Thanks for the PR, I've left a bunch of comments, let me know if you have questions.

2023-04-05 07:46 UTC, pyphilia commented on src/components/navigator/Navigator.tsx
> +      style={{ backgroundColor: '#f6f6f6' }}
Factor out the color in a variable in `constants`.

2023-04-05 07:46 UTC, pyphilia commented on src/components/navigator/util.tsx
> +  color: '#000000',
Why did you need to use black? Was the link blue? Try to use the `theme` color instead. I think `text.primary` might work? https://mui.com/system/palette/

2023-04-05 09:31 UTC, rayacers commented on src/components/navigator/Menu.tsx
> +        aria-haspopup="true"
I think it takes a string. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup.

2023-04-05 09:46 UTC, rayacers commented
Thanks for the review! I pushed the fix. Please let me know if there is any problem.

2023-04-17 09:31 UTC, pyphilia approved these changes

2023-04-17 09:32 UTC, merged