fix: translate tooltip at view selection
graasp/graasp-analytics pull request #262
Opened 2024-01-11 10:41 UTC by LinaYahya

closes #245

2024-01-15 09:31 UTC, pyphilia requested changes

2024-01-15 09:31 UTC, pyphilia commented on src/components/space/functionality/ViewSelect.tsx
> +        <Tooltip title={t(viewMessage)}>
I would actually add the `t` higher, so it's clear what's the string you translate.

2024-01-15 15:06 UTC, spaenleh approved these changes

2024-01-19 11:59 UTC, pyphilia approved these changes

2024-01-19 12:39 UTC, merged